[package]
name = "svg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg = "0.17.0"
rayon = "1.10.0"

crossbeam = "0.7.3"